config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  

  resources :books
  resources :authors
  resources :libraries
  # get '/coll', to: 'books#coll', as: 'coll'
  #get '/listauthors', to: 'authors#listauthors'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
   
    has_many :books, through: :authorbooks
    
    validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5 }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
 
    def index
      
        @authors = Author.all
        

        if params[:search_by_authorname] && params[:search_by_authorname] != ""
            @authors = Author.where("name LIKE ?","#{params[:search_by_authorname]}%")
          end
    end
    def show
        @author = Author.find(params[:id])
    end
    def new
        @author = Author.new
      end
    
      def create
        @author = Author.new(author_params)
    
        if @author.save
          redirect_to @author
        else
          render :new, status: :unprocessable_entity
        end
      end
      def edit
        @author = Author.find(params[:id])
      end
    
      def update
        @author = Author.find(params[:id])
    
        if @author.update(author_params)
          redirect_to @author
        else
          render :edit, status: :unprocessable_entity
        end
      end
      def destroy
        @author = Author.find(params[:id])
        @author.destroy
    
        redirect_to authors_path, status: :see_other
      end

     
      private
      def author_params
        params.require(:author).permit(:name, :description)
      end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with model: @author do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @author.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
    </div>
  
    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
      <% @author.errors.full_messages_for(:description).each do |message| %>
          <div><%= message %></div>
        <% end %>
    </div>

      
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/authors/edit.html.erb
<h1> Edit Author </h1>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<%= link_to 'Home', root_path %>
<%= form_tag "/authors", method: "GET" do %>
    <%= label_tag :Name %>
    <%= text_field_tag :search_by_authorname , params[:search_by_authorname ] %>
    <%= submit_tag "Search" %>
    <% end %>
  <br>
  <table  style = "border:2px solid black">
  <tr>
      <th  style = "border:1px solid black">Authors Name</th>
      <th  style = "border:1px solid black">Edit</th>
      <th  style = "border:1px solid black">Delete</th>
    </tr>
    <% @authors.each do |author| %>
    <tr>
    <td><%= link_to author.name, author %></td>
      <td style = "border:1px solid black"><%= link_to "Edit", edit_author_path(author) %></td>
      <td  style = "border:1px solid black"><%= link_to "Destroy", author_path(author), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></td>
    </tr>
    <% end %>
  </table>
  <br>
  <%= link_to "New Author", new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render "form", author: @author %>

app/views/authors/show.html.erb
<%= link_to 'Home', root_path %>
<h1>Name: <%= @author.name %></h1>
<h4>Author-ID:<%= @author.id %> </h4>


<p>Description: <%= @author.description %></p>

<h2> Books </h2>

<ul>
<% @author.books.each do |book| %>
    
    <li>
    <%= book.title %>
    </li>
   
    <% end %>
</ul>