config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  

  resources :books
  resources :authors
  resources :libraries
  # get '/coll', to: 'books#coll', as: 'coll'
  #get '/listauthors', to: 'authors#listauthors'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
 
  has_many :authorbooks
  has_many :authors, through: :authorbooks
 

  accepts_nested_attributes_for :authors, allow_destroy: true
  
  validates :title, presence: true, uniqueness: { scope: :title }
  validates :content, presence: true, length: { minimum: 5 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend
  load_and_authorize_resource
  
    def index
      # @books = Book.all
      @pagy, @books = pagy(Book.all, items:3)
      # @books = policy_scope(Book.all)
      # authorize @books
        if params[:search_by_bookname] && params[:search_by_bookname] != ""
        # @books = Book.where("title LIKE ?","#{params[:search_by_bookname]}%")
        @pagy, @books = pagy(Book.where("title LIKE ?","#{params[:search_by_bookname]}%"), items:3)
      end
    end
    def show
        @book = Book.find(params[:id])
        
    end
    def new
        @book = Book.new
        @book.authorbooks.build
          
       
      end
    
      def create
        @book = Book.new(book_params)
        
       
        if @book.save
          redirect_to @book
        else
          render :new, status: :unprocessable_entity
        end
      end
      def edit
        @book = Book.find(params[:id])
       

        
      end
    
      def update
        
        @book = Book.find(params[:id])
        
    
        if @book.update(book_params)
          redirect_to @book
        else
          render :edit, status: :unprocessable_entity
        end
      end
      def destroy
        @book = Book.find(params[:id])
        @book.destroy
    
        redirect_to books_path, status: :see_other
      end

     
      private
      def book_params
        params.require(:book).permit(:title, :content, :pages, authorbooks_attributes: [:id, :author_id, :_destroy])
      end
end

app/helpers/books_helper.rb
module BooksHelper
       
end

app/views/books/_authorbook_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
  <div>
    <%= f.label :author_id %>
    <%= f.collection_select :author_id, Author.all, :id, :name, multiple: true %>
  </div>
  
  <div>
    <%= link_to "Remove", '#', class: "remove_fields" %>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f| %>
    <div>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
      <% @book.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
        <% end %>
    </div>
  
    <div>
      <%= f.label :content %><br>
      <%= f.text_area :content %>
      <% @book.errors.full_messages_for(:content).each do |message| %>
          <div><%= message %></div>
        <% end %>
    </div>
    
    <div>
    <%= f.label :pages %><br>
    <%= f.text_field :pages %>
    <% @book.errors.full_messages_for(:pages).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <fieldset>
  <legend>Author:</legend>
  <%= f.fields_for :authorbooks do |author| %>
    <%= render "authorbook_fields", f: author %>
  <% end %>
  <%= link_to_add_fields "Add Author", f, :authorbooks %>
</fieldset>

    

    <div>
      <%= f.submit %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<h1> Edit Book </h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<%= link_to 'Home', root_path %>
<br>
<br>
<%= form_tag "/books", method: "GET" do %>
  <%= label_tag :Title %>
  <%= text_field_tag :search_by_bookname , params[:search_by_bookname ] %>
  <%= submit_tag "Search" %>
  <% end %>
<br>
<table  style = "border:2px solid black">
<tr>
    <th  style = "border:1px solid black">Books Title</th>
   
    <th  style = "border:1px solid black">Edit</th>
    <th  style = "border:1px solid black">Delete</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= link_to book.title, book %></td>
    
    
    <td style = "border:1px solid black"><%= link_to "Edit", edit_book_path(book) %></td>
    <td  style = "border:1px solid black"><%= link_to "Destroy", book_path(book), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %></td>
  </tr>
  <% end %>
  <tr>
  <td>
  <%== pagy_nav(@pagy) %>
  </td>
  </tr>
</table>


<br>
<%= link_to "New Book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<%= link_to 'Home', root_path %>
<h1>Title: <%= @book.title %></h1>
<span>Pages: <%= @book.pages %></span>

<p>Content: <%= @book.content %></p>